name: Get Koishi push date
on:
  workflow_dispatch:
  schedule:
    #    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install dependencies
      run: pip install requests
    - name: get date
      env: 
        DOCKERTOKEN: ${{ secrets.docker_token }}
      run: python koishi.py > docker/koishi
    - name: Commit
      run: |
        git config --global user.email 2095809794@qq.com
        git config --global user.name zglinus
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: master
        github_token: ${{ secrets.TOKEN }}
